### PR TITLE
Add ability to set docker user and command/entrypoint

### PR DESCRIPTION
**Pull request by lionelnicolas**
This adds support for `user`, `cmd` and `entrypoint` attributes, which can be set in the `browsers.json` config, and overridable using capabilities. If not set, the behavior remains unchanged: it's still going to use the `USER` and the `CMD` / `ENTRYPOINT` instruction set in the docker image.

This is useful to be able to use an alternative entrypoint at container startup, which may need to run administrative tasks in the container.

My current use-case for this is that I'm using an IPv6-enabled docker network, and in some tests I want to be able to run IPv6-only connectivity. To achieve that, I'm running a custom entrypoint before calling the existing `/entrypoint.sh`, which simply delete the IPv4 default route to break external IPv4 connectivity, based on an environment variable set from the capabilities.

```sh
# if IPv6 only is requested, delete the default IPv4 route to nuke IPv4 external connectivity
if [ "$(echo ${IPV6_ONLY:-} | tr '[A-Z]' '[a-z]')" = "true" ]; then
	ip -4 route del default || true
fi

exec /entrypoint.sh
```

I'm also thinking about creating a PR in https://github.com/aerokube/images/ to add support for pre/post hooks in the existing `entrypoint.sh`. So I could use `--volume /path/to/my/script:/entrypoint.pre.d/10-kill-ipv4:ro` when starting the browser containers, but I'll still need to be able to run the container as root.

### CODE REVIEW

**Comment by lionelnicolas** [comment]
Marking as draft for now as coverage tests will probably fail.

**Comment by lionelnicolas** [comment]
Added coverage for tests

**Comment by vania-pooh** [comment]
@lionelnicolas shouldn't this be implemented as custom Docker images instead?

**Comment by lionelnicolas** [comment]
Yeah I thought about that too, but I wanted to be able to use upstream selenoid images to avoid having to manage custom images.

**Comment by lionelnicolas** [comment]
@vania-pooh What do you think about this PR ? I think this is something that could be useful to some people. If you agree with that patch maybe I should update the documentation too.

Otherwise, feel free to close the PR, and then I'll handle custom docker images on my side.

**Review by cbasdev — APPROVED** [review]

**Comment by vania-pooh** [comment]
Let's not overcomplicate things.

**Pull request closed without merging**
