### PR TITLE
Video Instruction

### PR DESCRIPTION
**Pull request by MiluchOK**
Add video recording instructions to README

### CODE REVIEW

**Comment by vania-pooh** [comment]
Thank you for contribution! I think that this is one of possible ways to capture video with Selenoid. While there is no standard way let's move your instruction to StackOveflow. Created a new question for that: https://stackoverflow.com/questions/45364429/selenoid-recording-video-of-a-running-session

**Comment by lanwen** [comment]
Should be mentioned in docs

**Comment by vania-pooh** [comment]
@lanwen it should but I'm not sure whether we need to recommend exactly this script in docs. I would provide a ready to use container to capture video with zero effort.

**Comment by vania-pooh** [comment]
Posted your answer myself. Anyway thank you for contribution!

**Pull request closed without merging**
