### PR TITLE
Add healthcheck to selenoid image

### PR DESCRIPTION
**Pull request by giggio**
I've been using this in a locally built image for a while. I hope it helps.

### CODE REVIEW

**Comment by vania-pooh** [comment]
@giggio this HEALTCHECK stuff is known to be buggy in selenoid-ui image. I don't think we'll merge this.

**Comment by giggio** [comment]
@vania-pooh buggy how? Maybe I can help.

**Comment by giggio** [comment]
@vania-pooh We have alerts that let us know that a container is unhealthy so we can take proactive measures. That is the main reason, we don't need the badge.

**Comment by vania-pooh** [comment]
@giggio We added `/ping` API for that. Getting HTTP API health using `/ping` API is very standard approach and should be supported by the majority of monitoring systems.

**Comment by giggio** [comment]
@vania-pooh I was able to workaround it. I added a healthcheck to the docker-compose file, like so (only showing beginning of the file):

```yml
version: '3.7'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    healthcheck:
      test: ["CMD", "sh", "-c", "apk add curl && curl -fs http://localhost:4444/ping"]
      interval: 60s
      timeout: 3s
      retries: 3
```

Feel free to close the PR if you don't see value in it.

**Pull request closed without merging**
