### PR TITLE
Fixed url on video doc page

### PR DESCRIPTION
**Pull request by kudodenko**

### CODE REVIEW

**Comment by vania-pooh** [comment]
@kudodenko don't get the reason of replacing internal Asciidoc URLs with hard-coded external URLs.

**Comment by kudodenko** [comment]
@vania-pooh sorry but this block absent on this page now

**Comment by vania-pooh** [comment]
@kudodenko here it is: https://aerokube.com/selenoid/latest/#_special_capabilities

**Comment by kudodenko** [comment]
@vania-pooh, thanks

**Pull request closed without merging**
