### PR TITLE
Selenoid with Kubernetes support

### PR DESCRIPTION
**Pull request by alcounit**

### CODE REVIEW

**Comment by vania-pooh** [comment]
@alcounit have you seen [Moon](https://github.com/aerokube/moon) which does exactly the same but more efficiently?

**Comment by alcounit** [comment]
@vania-pooh yes, I saw. I just want to propose minimal support for K8, all other extended features can be supported by Moon same as premium support.

**Comment by vania-pooh** [comment]
@alcounit we have several considerations about Kubernetes in Selenoid:
1) We are trying to develop Selenoid as simple as possible. Even now it has a lot of sophisticated features like VNC, clipboard or devtools support. So adding Kubernetes support here is one more complication.
2) Selenoid architecture is stateful, i.e. is not adapted for multiple replicas behind load balancer and will lose all running sessions if OOM killer arrives. So basically we consider adding Kubernetes support a bad idea without changing Selenoid internal architecture. But all respective changes were already made in Moon so it makes no sense.
3) We have a similar PR (#455) related to Mesos support and our idea is to have a separate project based on Selenoid code. This is why it not still merged since May, 2018. Otherwise adding more and more features will sooner or later explode Selenoid code quality or our brain.
4) Having basic Kubernetes support users will sooner or later require more advanced features. We are a relatively small team and have no resources to deliver this.

Having said that, if you wish - you can move all Selenoid code to a separate repository and add Kubernetes support there: it's open source.

**Comment by alcounit** [comment]
@vania-pooh I understand, anyway thanks for your time.

**Pull request closed without merging**
